# 1、numpy 数组 索引

- **索引分为三个参数 : : : ,其中每个参数都可以忽略，具体参数为:**  
    **1. 参数1:起始行（列）的索引**  
    **2.参数2：终点行（列）的索引值**  
    **3.参数3：步进数**    

**注意：以上索引均为左闭右开区间[参数1，参数2)**

In [1]:
import numpy as np

In [2]:
# 定义矩阵的行数和列数
rows = 9
cols = 10

# 创建一个矩阵，其每个元素的值等于其所在的行索引
matrix = np.arange(rows)[:, np.newaxis] * np.ones((1, cols))
matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

**问题1: matrixs是如何做到其每个元素的值等于其所在的行索引，其中 np.newaxis 的作用是什么？**

In [3]:
# 行索引2 （即第三行）开始步进，步距为2打印行号2，4，6，8
a = matrix[2::2,:]
a

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [4]:
# 从行索引1 步进到行索引5，步距为2 打印行索引：1，3，左闭右开所以不到 5
b = matrix[1:5:2,:]
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [5]:
# 行索引1 步进到行索引 5，步进为 -1 ，由于步进为-1无法到达，所以为空
c = matrix[1:5:-1,:]
c

array([], shape=(0, 10), dtype=float64)

In [6]:
# 行索引5 步进到行索引 1，步进为 -1 ，打印行索引为 5，4，3，2
d = matrix[5:1:-1,:]
d

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

### 未指定时，起始索引是从哪个值开始的？？

In [7]:
e = matrix[::-1,:]
e

array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
# 测试未指定起始索引时，是从哪个值开始的
e1 = matrix[:5:1,:]
e1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [9]:
# 测试未指定起始索引时，是从哪个值开始的
e2 = matrix[:5:-1,:]
e2

array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

### **结论：为指定起始索引时，根据步进正负，自动设定起始索引。步进为正数时，默认起始索引为0，步进为负数时，默认起始索引为最大索引**

In [10]:
e = matrix[2::-1,:]
e

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
index = np.arange(9)
index

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
matrix[index[::2],1]

array([0., 2., 4., 6., 8.])