In [1]:
import torch

In [2]:
rows = 9
cols = 10

tensor = torch.arange(rows).repeat(cols,1).T
tensor,tensor.shape

(tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
         [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
         [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
         [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
         [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
         [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]]),
 torch.Size([9, 10]))

In [3]:
# tensor 不支持 负数步距
# tensor  = tensor[::-1,:]

In [4]:
tensorB = torch.flip(tensor,dims=[0])
tensorB

tensor([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
        [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
# ** 是幂运算
tensor + tensorB,tensor ** tensorB

(tensor([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
         [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
         [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
         [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
         [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
         [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
         [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
         [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
         [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]]),
 tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
         [ 64,  64,  64,  64,  64,  64,  64,  64,  64,  64],
         [243, 243, 243, 243, 243, 243, 243, 243, 243, 243],
         [256, 256, 256, 256, 256, 256, 256, 256, 256, 256],
         [125, 125, 125, 125, 125, 125, 125, 125, 125, 125],
         [ 36,  36,  36,  36,  36,  36,  36,  36,  36,  36],
         [  7,   7,   7,   7,   7,   7,   7,   7,   7,   7],
         [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1]]))

In [6]:
tensorC = torch.arange(12).reshape((3,4))
tensorC

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
tensor.shape,tensorB.shape,tensorC.shape

(torch.Size([9, 10]), torch.Size([9, 10]), torch.Size([3, 4]))

In [8]:
# tensor + tensorC

In [9]:
tensorC = tensorC.reshape((12,1))
tensorC,tensorC.shape

(tensor([[ 0],
         [ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11]]),
 torch.Size([12, 1]))

In [10]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b,a+b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [11]:
tensorD = tensor.reshape((1,90))
tensorD,tensorD.shape

(tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7,
          7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]]),
 torch.Size([1, 90]))

In [12]:
tensorC + tensorD 

tensor([[ 0,  0,  0,  ...,  8,  8,  8],
        [ 1,  1,  1,  ...,  9,  9,  9],
        [ 2,  2,  2,  ..., 10, 10, 10],
        ...,
        [ 9,  9,  9,  ..., 17, 17, 17],
        [10, 10, 10,  ..., 18, 18, 18],
        [11, 11, 11,  ..., 19, 19, 19]])

**广播机制必须是维度相同，且对应维度形状相同或者其中一个维度形状为1.**

### 内存问题

In [13]:
tensor,tensor.shape

(tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
         [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
         [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
         [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
         [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
         [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]]),
 torch.Size([9, 10]))

**执行运算时，即使赋值为同一个变量，依旧相当于 开辟新内存后销毁之前状态，内存交换增加**  
**id 函数相当于得到地址**

In [14]:
addr = id(tensor)
tensor = tensor + tensorB
id(tensor) == addr

False

**对元素进行操作，则不会更改内存空间**

In [15]:
addr = id(tensor)
tensor[:] = tensor + tensorB
id(tensor) == addr

True

**直接进行赋值操作，不会因为新的变量名而开辟新的内存空间，两个变量共有一块内存区域。此时修改tensorA同时也是在修改tensor**

In [16]:
tensorA = tensor
id(tensor) == id(tensorA),tensorA

(True,
 tensor([[16, 16, 16, 16, 16, 16, 16, 16, 16, 16],
         [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
         [14, 14, 14, 14, 14, 14, 14, 14, 14, 14],
         [13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
         [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
         [11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
         [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
         [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
         [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8]]))

In [17]:
# 修改tensorA的同时tensor也在变换
tensorA[0,0] = 10 
tensorA,tensor

(tensor([[10, 16, 16, 16, 16, 16, 16, 16, 16, 16],
         [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
         [14, 14, 14, 14, 14, 14, 14, 14, 14, 14],
         [13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
         [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
         [11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
         [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
         [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
         [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8]]),
 tensor([[10, 16, 16, 16, 16, 16, 16, 16, 16, 16],
         [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
         [14, 14, 14, 14, 14, 14, 14, 14, 14, 14],
         [13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
         [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
         [11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
         [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
         [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
         [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8]]))

**使用clone，可以为新变量开辟新的内存，此时tensorA与tensor无关**

In [18]:
tensorA = tensor.clone()
id(tensor) == id(tensorA),tensorA

(False,
 tensor([[10, 16, 16, 16, 16, 16, 16, 16, 16, 16],
         [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
         [14, 14, 14, 14, 14, 14, 14, 14, 14, 14],
         [13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
         [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
         [11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
         [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
         [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
         [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8]]))

In [19]:
# 修改tensorA，tensor不会变化
tensorA[0,0] = 16 
tensorA,tensor

(tensor([[16, 16, 16, 16, 16, 16, 16, 16, 16, 16],
         [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
         [14, 14, 14, 14, 14, 14, 14, 14, 14, 14],
         [13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
         [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
         [11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
         [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
         [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
         [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8]]),
 tensor([[10, 16, 16, 16, 16, 16, 16, 16, 16, 16],
         [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
         [14, 14, 14, 14, 14, 14, 14, 14, 14, 14],
         [13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
         [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
         [11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
         [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
         [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
         [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8]]))

### sum  
**axis参数是维数从大到小。axis=0代表最高维。**  
**axis的维数个人理解并非是平等的，而是分阶层的。例如3*3的矩阵**  

[[1,2,3],[4,5,6],[7,8,9]]  
axis=0,该维度下的元素为[1,2,3]...  
axis=1该维度下的元素为 1,2...  
对应维度相加即是以什么维度下的元素为单位相加。so：

In [20]:
tensor = tensor.reshape((1,3,3,10))
tensor,tensor.shape

(tensor([[[[10, 16, 16, 16, 16, 16, 16, 16, 16, 16],
           [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
           [14, 14, 14, 14, 14, 14, 14, 14, 14, 14]],
 
          [[13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
           [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
           [11, 11, 11, 11, 11, 11, 11, 11, 11, 11]],
 
          [[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
           [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
           [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8]]]]),
 torch.Size([1, 3, 3, 10]))

In [21]:
tensor.sum(),tensor.sum().shape

(tensor(1074), torch.Size([]))

In [59]:
a = tensor.sum(axis=0)
tensor,a,a.shape

(tensor([[[[10, 16, 16, 16, 16, 16, 16, 16, 16, 16],
           [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
           [14, 14, 14, 14, 14, 14, 14, 14, 14, 14]],
 
          [[13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
           [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
           [11, 11, 11, 11, 11, 11, 11, 11, 11, 11]],
 
          [[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
           [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
           [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8]]]]),
 tensor([[[10, 16, 16, 16, 16, 16, 16, 16, 16, 16],
          [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
          [14, 14, 14, 14, 14, 14, 14, 14, 14, 14]],
 
         [[13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
          [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
          [11, 11, 11, 11, 11, 11, 11, 11, 11, 11]],
 
         [[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
          [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
          [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8]]]),
 torch.Size([3, 3, 10]))

In [29]:
a = tensor.sum(axis=1)
tensor,a,a.shape

(tensor([[[[10, 16, 16, 16, 16, 16, 16, 16, 16, 16],
           [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
           [14, 14, 14, 14, 14, 14, 14, 14, 14, 14]],
 
          [[13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
           [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
           [11, 11, 11, 11, 11, 11, 11, 11, 11, 11]],
 
          [[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
           [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
           [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8]]]]),
 tensor([[[33, 39, 39, 39, 39, 39, 39, 39, 39, 39],
          [36, 36, 36, 36, 36, 36, 36, 36, 36, 36],
          [33, 33, 33, 33, 33, 33, 33, 33, 33, 33]]]),
 torch.Size([1, 3, 10]))

In [60]:
a = tensor.sum(axis=2)
a,tensor.shape,a.shape

(tensor([[[39, 45, 45, 45, 45, 45, 45, 45, 45, 45],
          [36, 36, 36, 36, 36, 36, 36, 36, 36, 36],
          [27, 27, 27, 27, 27, 27, 27, 27, 27, 27]]]),
 torch.Size([1, 3, 3, 10]),
 torch.Size([1, 3, 10]))

In [61]:
a = tensor.sum(axis=3)
a,tensor.shape,a.shape

(tensor([[[154, 150, 140],
          [130, 120, 110],
          [100,  90,  80]]]),
 torch.Size([1, 3, 3, 10]),
 torch.Size([1, 3, 3]))

**axis=(\*1,\*2)时，相当于先进行\*1维度的相加，再进行\*2维度的。也可以将两个步骤交换**

In [63]:
a = tensor.sum(axis=(1,2))
a,tensor,tensor.shape,a.shape

(tensor([[102, 108, 108, 108, 108, 108, 108, 108, 108, 108]]),
 tensor([[[[10, 16, 16, 16, 16, 16, 16, 16, 16, 16],
           [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
           [14, 14, 14, 14, 14, 14, 14, 14, 14, 14]],
 
          [[13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
           [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
           [11, 11, 11, 11, 11, 11, 11, 11, 11, 11]],
 
          [[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
           [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
           [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8]]]]),
 torch.Size([1, 3, 3, 10]),
 torch.Size([1, 10]))

**keepdims=True,保存维度数不变，被加的轴 轴长变为1，便于使用广播机制进行运算**

In [25]:
a = tensor.sum(axis=1,keepdims=True)
a,a.shape

(tensor([[[[33, 39, 39, 39, 39, 39, 39, 39, 39, 39],
           [36, 36, 36, 36, 36, 36, 36, 36, 36, 36],
           [33, 33, 33, 33, 33, 33, 33, 33, 33, 33]]]]),
 torch.Size([1, 1, 3, 10]))

In [26]:
a/tensor,a.shape,tensor.shape,(a/tensor).shape

(tensor([[[[3.3000, 2.4375, 2.4375, 2.4375, 2.4375, 2.4375, 2.4375, 2.4375,
            2.4375, 2.4375],
           [2.4000, 2.4000, 2.4000, 2.4000, 2.4000, 2.4000, 2.4000, 2.4000,
            2.4000, 2.4000],
           [2.3571, 2.3571, 2.3571, 2.3571, 2.3571, 2.3571, 2.3571, 2.3571,
            2.3571, 2.3571]],
 
          [[2.5385, 3.0000, 3.0000, 3.0000, 3.0000, 3.0000, 3.0000, 3.0000,
            3.0000, 3.0000],
           [3.0000, 3.0000, 3.0000, 3.0000, 3.0000, 3.0000, 3.0000, 3.0000,
            3.0000, 3.0000],
           [3.0000, 3.0000, 3.0000, 3.0000, 3.0000, 3.0000, 3.0000, 3.0000,
            3.0000, 3.0000]],
 
          [[3.3000, 3.9000, 3.9000, 3.9000, 3.9000, 3.9000, 3.9000, 3.9000,
            3.9000, 3.9000],
           [4.0000, 4.0000, 4.0000, 4.0000, 4.0000, 4.0000, 4.0000, 4.0000,
            4.0000, 4.0000],
           [4.1250, 4.1250, 4.1250, 4.1250, 4.1250, 4.1250, 4.1250, 4.1250,
            4.1250, 4.1250]]]]),
 torch.Size([1, 1, 3, 10]),
 torch.Size([1, 3

### 累加求和 cumsum

In [30]:
a = tensor.cumsum(axis = 1)
tensor,tensor.shape,a,a.shape

(tensor([[[[10, 16, 16, 16, 16, 16, 16, 16, 16, 16],
           [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
           [14, 14, 14, 14, 14, 14, 14, 14, 14, 14]],
 
          [[13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
           [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
           [11, 11, 11, 11, 11, 11, 11, 11, 11, 11]],
 
          [[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
           [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
           [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8]]]]),
 torch.Size([1, 3, 3, 10]),
 tensor([[[[10, 16, 16, 16, 16, 16, 16, 16, 16, 16],
           [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
           [14, 14, 14, 14, 14, 14, 14, 14, 14, 14]],
 
          [[23, 29, 29, 29, 29, 29, 29, 29, 29, 29],
           [27, 27, 27, 27, 27, 27, 27, 27, 27, 27],
           [25, 25, 25, 25, 25, 25, 25, 25, 25, 25]],
 
          [[33, 39, 39, 39, 39, 39, 39, 39, 39, 39],
           [36, 36, 36, 36, 36, 36, 36, 36, 36, 36],
           [33, 33, 33, 33, 33, 33, 33, 33, 33, 33]]]])

In [36]:
a[:,-1,:,:],tensor.sum(axis=1),tensor.sum(axis=1).shape, a[:,-1,:,:].shape

(tensor([[[33, 39, 39, 39, 39, 39, 39, 39, 39, 39],
          [36, 36, 36, 36, 36, 36, 36, 36, 36, 36],
          [33, 33, 33, 33, 33, 33, 33, 33, 33, 33]]]),
 tensor([[[33, 39, 39, 39, 39, 39, 39, 39, 39, 39],
          [36, 36, 36, 36, 36, 36, 36, 36, 36, 36],
          [33, 33, 33, 33, 33, 33, 33, 33, 33, 33]]]),
 torch.Size([1, 3, 10]),
 torch.Size([1, 3, 10]))

### 向量点积

In [44]:
a = torch.arange(0,12,2)
b = torch.arange(6)
a,a.shape,b,b.shape

(tensor([ 0,  2,  4,  6,  8, 10]),
 torch.Size([6]),
 tensor([0, 1, 2, 3, 4, 5]),
 torch.Size([6]))

In [46]:
torch.dot(a,b),a*b,torch.sum(a*b)

(tensor(110), tensor([ 0,  2,  8, 18, 32, 50]), tensor(110))

### 矩阵与向量相乘

In [49]:
tensor,tensor.shape

(tensor([[[[10, 16, 16, 16, 16, 16, 16, 16, 16, 16],
           [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
           [14, 14, 14, 14, 14, 14, 14, 14, 14, 14]],
 
          [[13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
           [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
           [11, 11, 11, 11, 11, 11, 11, 11, 11, 11]],
 
          [[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
           [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
           [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8]]]]),
 torch.Size([1, 3, 3, 10]))

In [51]:
tensorB,tensorB.shape

(tensor([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
         [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
         [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
         [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
         [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
         [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
         [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
 torch.Size([9, 10]))

In [52]:
a = torch.arange(10)
a,torch.mv(tensorB,a),torch.mv(tensorB,a).shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([360, 315, 270, 225, 180, 135,  90,  45,   0]),
 torch.Size([9]))

### 矩阵相乘

In [56]:
tensorA,tensorA.shape

(tensor([[16, 16, 16, 16, 16, 16, 16, 16, 16, 16],
         [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
         [14, 14, 14, 14, 14, 14, 14, 14, 14, 14],
         [13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
         [12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
         [11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
         [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
         [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
         [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8]]),
 torch.Size([9, 10]))

In [58]:
b = torch.mm(tensorA.T,tensorB)
b,b.shape

(tensor([[492, 492, 492, 492, 492, 492, 492, 492, 492, 492],
         [492, 492, 492, 492, 492, 492, 492, 492, 492, 492],
         [492, 492, 492, 492, 492, 492, 492, 492, 492, 492],
         [492, 492, 492, 492, 492, 492, 492, 492, 492, 492],
         [492, 492, 492, 492, 492, 492, 492, 492, 492, 492],
         [492, 492, 492, 492, 492, 492, 492, 492, 492, 492],
         [492, 492, 492, 492, 492, 492, 492, 492, 492, 492],
         [492, 492, 492, 492, 492, 492, 492, 492, 492, 492],
         [492, 492, 492, 492, 492, 492, 492, 492, 492, 492],
         [492, 492, 492, 492, 492, 492, 492, 492, 492, 492]]),
 torch.Size([10, 10]))