In [1]:
import numpy as np

In [2]:
import torch

In [3]:
from torch.utils import data

In [4]:
def synthetic_data(true_w,true_b,num_examples):
    features = torch.normal(0,1,(num_examples,len(true_w)))
    labels = torch.matmul(features,true_w)+true_b
    labels += labels + torch.normal(0,0.01,labels.shape)
    # print(features.shape,labels.shape)
    return features,labels.reshape((-1,1))

In [5]:
true_w = torch.tensor([2,-3.4])
true_b = 4.2
features,labels = synthetic_data(true_w,true_b,1000)
labels

tensor([[ 1.8795e+01],
        [ 1.2928e+00],
        [-2.5566e+00],
        [ 1.2892e+00],
        [ 1.6728e+01],
        [ 1.2153e+01],
        [ 8.8793e+00],
        [ 8.9721e+00],
        [ 2.7672e+00],
        [ 6.7840e+00],
        [ 9.7366e+00],
        [ 6.6870e+00],
        [ 1.0759e+01],
        [ 5.4933e+00],
        [ 9.7991e+00],
        [ 2.1687e+01],
        [ 1.1282e+01],
        [-5.8005e+00],
        [ 7.8006e+00],
        [ 1.1189e+01],
        [ 1.0583e+01],
        [ 4.5710e+00],
        [ 1.0993e+01],
        [ 2.0982e+01],
        [-7.6176e-01],
        [ 6.9019e-01],
        [ 7.6489e+00],
        [-1.0221e+01],
        [-2.2816e-01],
        [-9.4096e+00],
        [ 3.1612e-01],
        [-1.8974e+00],
        [ 9.2208e+00],
        [ 1.5958e+01],
        [ 2.2191e+00],
        [ 8.0470e+00],
        [ 1.3358e+01],
        [ 1.5225e+01],
        [ 1.4236e+01],
        [ 7.9152e+00],
        [ 2.0728e-01],
        [ 1.9565e+01],
        [ 7.5106e+00],
        [ 1

TensorDataset 需要输入第一维度相同的张量，数量任意，进行组合

In [6]:
dataset = data.TensorDataset(features,labels, features)
features[0],labels[0],dataset[0]

(tensor([ 0.6615, -1.1394]),
 tensor([18.7951]),
 (tensor([ 0.6615, -1.1394]), tensor([18.7951]), tensor([ 0.6615, -1.1394])))

In [7]:
data_arrays = (features,labels)
print(*data_arrays)

tensor([[ 0.6615, -1.1394],
        [-0.6135,  0.6845],
        [-1.3801,  0.8008],
        ...,
        [-1.1490, -0.0789],
        [ 1.7127, -1.0832],
        [ 1.8524, -0.6225]]) tensor([[ 1.8795e+01],
        [ 1.2928e+00],
        [-2.5566e+00],
        [ 1.2892e+00],
        [ 1.6728e+01],
        [ 1.2153e+01],
        [ 8.8793e+00],
        [ 8.9721e+00],
        [ 2.7672e+00],
        [ 6.7840e+00],
        [ 9.7366e+00],
        [ 6.6870e+00],
        [ 1.0759e+01],
        [ 5.4933e+00],
        [ 9.7991e+00],
        [ 2.1687e+01],
        [ 1.1282e+01],
        [-5.8005e+00],
        [ 7.8006e+00],
        [ 1.1189e+01],
        [ 1.0583e+01],
        [ 4.5710e+00],
        [ 1.0993e+01],
        [ 2.0982e+01],
        [-7.6176e-01],
        [ 6.9019e-01],
        [ 7.6489e+00],
        [-1.0221e+01],
        [-2.2816e-01],
        [-9.4096e+00],
        [ 3.1612e-01],
        [-1.8974e+00],
        [ 9.2208e+00],
        [ 1.5958e+01],
        [ 2.2191e+00],
        [ 8.0

DataLoader 是一个**可迭代对象**，可以使用for 循环遍历。 可以认为Dataset是一个仓库,而DataLoader是将Dataset按照batch打包完成的仓库，里面存储要遍历的对象。  
`iter(data_iter)`创建 DataLoader的**迭代器**，可以使用`next()`函数来遍历对象。

In [8]:
def load_array(data_arrays, batch_size, is_train=True):
    """构造Pytorch 数据迭代器"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset,batch_size,shuffle=is_train)

In [9]:
batch_size = 10
data_iter = load_array((features,labels),batch_size)
for batch in data_iter:
    print(batch)
    break
# type(data_iter), next(iter(data_iter))
data_iter

[tensor([[-0.8100, -0.1207],
        [-0.5597, -1.2248],
        [ 0.4046,  1.7263],
        [-1.4506, -1.1601],
        [ 0.3000, -0.0921],
        [ 0.2137,  1.0339],
        [-0.6646,  1.2606],
        [ 1.3253,  0.7810],
        [-0.1869, -0.0677],
        [ 1.0230,  1.2912]]), tensor([[ 5.9820],
        [14.4866],
        [-1.7244],
        [10.4805],
        [10.2121],
        [ 2.1994],
        [-2.8250],
        [ 8.3884],
        [ 8.1066],
        [ 3.7008]])]


In [10]:
from torch import nn
net  = nn.Sequential(nn.Linear(2,1))
net

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
)

`Module.parameters()`返回的是一个**迭代器对象**,在需要的时候才将值存入内存.

In [11]:
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)
for para in net.parameters():
    print(para)
net[0],net.parameters(),next(net.parameters())

Parameter containing:
tensor([[-0.0024,  0.0086]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


(Linear(in_features=2, out_features=1, bias=True),
 <generator object Module.parameters at 0x000001FD3B0312A0>,
 Parameter containing:
 tensor([[-0.0024,  0.0086]], requires_grad=True))

In [12]:
loss = nn.MSELoss()
loss

MSELoss()

In [13]:
trainer = torch.optim.SGD(net.parameters(),lr=0.03)

In [14]:
num_epochs = 5
for epoch in range(num_epochs):
    for X,y in data_iter:
        l = loss(net(X),y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features),labels)
    print(f'epoch {epoch + 1},loss {l:f}')

epoch 1,loss 0.000566
epoch 2,loss 0.000097
epoch 3,loss 0.000098
epoch 4,loss 0.000098
epoch 5,loss 0.000098


注意**输出形状**和**真值的形状**要匹配,否则会触发不必要的广播机制

In [17]:
features.shape,net(features).shape,labels.shape,X.shape,y.shape

(torch.Size([1000, 2]),
 torch.Size([1000, 1]),
 torch.Size([1000, 1]),
 torch.Size([10, 2]),
 torch.Size([10, 1]))

In [18]:
w = net[0].weight.data
print('w的估计误差：', (true_w - w.reshape(true_w.shape))/true_w)
b = net[0].bias.data
print('b的估计误差：', (true_b - b)/true_b)
w,b,true_w,true_b

w的估计误差： tensor([-1.0000, -1.0001])
b的估计误差： tensor([-1.0001])


(tensor([[ 4.0000, -6.8005]]),
 tensor([8.4002]),
 tensor([ 2.0000, -3.4000]),
 4.2)