In [10]:
import torch
from torch import nn
from torch.nn import functional as F
torch.device('cuda'),torch.cuda.device('cuda'),torch.cuda.device_count()

(device(type='cuda'), <torch.cuda.device at 0x2243c580c50>, 1)

In [12]:
def try_gpu(i=0):
    if torch.cuda.device_count() >= i+1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

In [13]:
def try_all_gpus():
    """返回所有可用的GPU，若没有GPU，则返回cpu"""
    devices = [torch.device(f'cuda:{i}')for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

In [14]:
try_all_gpus()

[device(type='cuda', index=0)]

In [15]:
x = torch.tensor([1.,2.,3.,4.])
x.device

device(type='cpu')

In [16]:
x = torch.tensor([1.,2.,3.,4.],device =try_gpu() )
x.device

device(type='cuda', index=0)

In [17]:
y = torch.tensor([1.,2.,3.,4.],device =try_gpu())
y.device

device(type='cuda', index=0)

In [20]:
z = x.cuda(0)
print(z)

tensor([1., 2., 3., 4.], device='cuda:0')


In [21]:
z+y

tensor([2., 4., 6., 8.], device='cuda:0')

module只能使用.to(device=try_gpu())

In [23]:
net = nn.Linear(4,1)
net = net.to(device=try_gpu())
net(x)

tensor([-2.5999], device='cuda:0', grad_fn=<ViewBackward0>)

In [24]:
net.weight.data.device

device(type='cuda', index=0)