### 池化层

In [2]:
import torch
import torch.nn as nn

In [4]:
pool2d = nn.MaxPool2d(3)

In [5]:
X = torch.arange(16,dtype = torch.float32).reshape((1,1,4,4))

In [6]:
pool2d(X)

tensor([[[[10.]]]])

In [10]:
pool2d = nn.MaxPool2d((2,3),padding=1,stride=2)

In [11]:
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

In [15]:
pool2d = nn.MaxPool2d((2,3),padding=(1,1),stride=(2,3))

In [16]:
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])