In [1]:
import numpy as np
from torch.utils.data import Dataset

In [2]:
help(Dataset)

Help on class Dataset in module torch.utils.data.dataset:

class Dataset(typing.Generic)
 |  An abstract class representing a :class:`Dataset`.
 |
 |  All datasets that represent a map from keys to data samples should subclass
 |  it. All subclasses should overwrite :meth:`__getitem__`, supporting fetching a
 |  data sample for a given key. Subclasses could also optionally overwrite
 |  :meth:`__len__`, which is expected to return the size of the dataset by many
 |  :class:`~torch.utils.data.Sampler` implementations and the default options
 |  of :class:`~torch.utils.data.DataLoader`. Subclasses could also
 |  optionally implement :meth:`__getitems__`, for speedup batched samples
 |  loading. This method accepts list of indices of samples of batch and returns
 |  list of samples.
 |
 |  .. note::
 |    :class:`~torch.utils.data.DataLoader` by default constructs an index
 |    sampler that yields integral indices.  To make it work with a map-style
 |    dataset with non-integral indices

### **Dataset** 是一个抽象类，需要重写其 __\_\_getitem\_\_(self, index)__ 和 __\_\_len\_\_(self)__

In [3]:
class MyDataset(Dataset):
    def __init__(self):
        super().__init__()
        self.x = np.random.random((10,10))
        self.w = np.random.random(10)
        self.y = self.x *self.w
    def __len__(self):
        return len(self.x)
    def __getitem__(self,idx):
        return self.x[idx,:],self.y[idx,:]
        print(idx)
    

In [4]:
data = MyDataset()

In [5]:
len(data)

10

In [6]:
x,y = data[0]
x,y,x.shape

(array([0.74634056, 0.99517752, 0.38925949, 0.63587857, 0.31246164,
        0.02378562, 0.48151424, 0.87490874, 0.18426083, 0.51943938]),
 array([0.21725383, 0.96536049, 0.15109589, 0.5445634 , 0.07364715,
        0.01633778, 0.38877726, 0.63184524, 0.02802711, 0.40872659]),
 (10,))

### **Dataset** 相当于 数据仓库，**dataloader** 相当于 数据加载器 （搬运工）

#### dataloader 常用参数
batch_size ：批量大小  
shuffle: 是否乱序  
sample：  
batch_sample:  
num_workers :多线程加载，但是在windows 下容易出现问题  
drop_last:  

In [7]:
from torch.utils.data import DataLoader

In [8]:
data_loader = DataLoader(data,batch_size=4,shuffle=True)

In [9]:
for data in data_loader:
    x,y = data
    print(x,y)
    print(x.shape,y.shape)
    break

tensor([[0.3340, 0.8133, 0.2960, 0.9662, 0.3736, 0.2439, 0.4238, 0.6362, 0.4207,
         0.5422],
        [0.4674, 0.1021, 0.0827, 0.4876, 0.3482, 0.0202, 0.6445, 0.5488, 0.4897,
         0.6074],
        [0.5550, 0.9291, 0.1064, 0.3912, 0.2045, 0.2607, 0.0993, 0.0830, 0.2994,
         0.4883],
        [0.9965, 0.5916, 0.4145, 0.3811, 0.2242, 0.9735, 0.1751, 0.1411, 0.6932,
         0.4711]], dtype=torch.float64) tensor([[0.0972, 0.7890, 0.1149, 0.8274, 0.0881, 0.1676, 0.3422, 0.4594, 0.0640,
         0.4267],
        [0.1361, 0.0990, 0.0321, 0.4176, 0.0821, 0.0139, 0.5203, 0.3963, 0.0745,
         0.4780],
        [0.1616, 0.9012, 0.0413, 0.3350, 0.0482, 0.1791, 0.0801, 0.0599, 0.0455,
         0.3842],
        [0.2901, 0.5739, 0.1609, 0.3263, 0.0528, 0.6687, 0.1414, 0.1019, 0.1054,
         0.3707]], dtype=torch.float64)
torch.Size([4, 10]) torch.Size([4, 10])
